Event batching
aptabase/aptabase-unity pull request #2
Opened 2023-08-29 19:34 UTC by NikTheNak

2023-09-06 21:14 UTC, goenning commented on README.md
> +App Version is automatically detected, but you can override it with the `AppVersion` field. You will need to provide a `AppBuildNumber` as it may vary across different platforms. This allows you to s
As AppBuilderNumber is optional, should we have something like this instead?
```
You may want to provide a `AppBuildNumber` as ...
```

2023-09-06 21:16 UTC, goenning commented on Runtime/Dispatcher.cs
> +        private const string EVENT_ENDPOINT = "/api/v0/event";
I assume we no longer need this?

2023-09-06 21:17 UTC, goenning commented on Runtime/Environment.cs
> +                    operatingSystem.osName = "maxOS";
macOS :)

2023-09-06 21:20 UTC, goenning requested changes
looks good to me, just a few minor comments.

Is is common to copy thirdparty dependencies in Unity? We can't use nuget?

2023-09-07 16:27 UTC, NikTheNak commented on Runtime/Dispatcher.cs
> +        private const string EVENT_ENDPOINT = "/api/v0/event";
I left in for single events, but yeah not needed. Will remove

2023-09-07 16:28 UTC, NikTheNak commented on Runtime/Environment.cs
> +                    operatingSystem.osName = "maxOS";
oops! updating

2023-09-07 21:17 UTC, NikTheNak commented
> Is is common to copy thirdparty dependencies in Unity? We can't use nuget?
From all the packages I use yes. Have to do some workarounds to get it to work out of the box. We could load in Newtonsoft via package manager, but that could lead to other issues.

2023-09-08 12:41 UTC, merged

2023-09-08 12:41 UTC, goenning commented
Thanks! Going to tag this as 0.2.0 🎉